version: "3"
services:
  burger-web:
    container_name: burger-web
    image: nginx
    restart: unless-stopped
    ports:
      - 7123:7123
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/usr/share/nginx/html